package com.hacaller.ardistanceopengles20.shader;

import android.opengl.GLES20;
import android.util.Log;

import org.artoolkit.ar.base.rendering.gles20.BaseShaderProgram;
import org.artoolkit.ar.base.rendering.gles20.OpenGLShader;

import java.nio.ByteBuffer;
import java.nio.FloatBuffer;

/**
 * Created by Herbert Caller on 30/11/2017.
 */
/**
 * Created by Thorsten Bux on 25.01.2016.
 * <p/>
 * The shader program links together the vertex shader and the fragment shader and compiles them.
 * It also is responsible for binding the attributes. Attributes can be used to pass in values to the
 * shader during runtime.
 *
 * Finally it renders the given geometry.
 */
public class MarkerDistanceShaderProgram extends BaseShaderProgram {

    private static final String TAG = "MarkerDistanceShader";
    private int lineWidth;

    public MarkerDistanceShaderProgram(OpenGLShader vertexShader, OpenGLShader fragmentShader, int lineWidth) {
        super(vertexShader, fragmentShader);
        this.lineWidth = lineWidth;
    }

    public void setLineWidth(int lineWidth) {
        this.lineWidth = lineWidth;
    }

    @Override
    public int getProjectionMatrixHandle() {
        return super.getProjectionMatrixHandle();
    }

    @Override
    public int getModelViewMatrixHandle() {
        return super.getModelViewMatrixHandle();
    }

    @Override
    protected void bindAttributes() {
        super.bindAttributes();
    }

    public int getColorHandle() {
        return GLES20.glGetUniformLocation(shaderProgramHandle, MarkerDistanceFragmentShader.colorVectorString);
    }

    /**
     * There are several render methods available from the base class. In this case we override the {@link #render(FloatBuffer, FloatBuffer, ByteBuffer)} one.
     * Although we never use the index ByteBuffer.
     * We pass in the vertex and color information from the {@link org.artoolkit.ar.base.rendering.gles20.LineGLES20} object.
     *
     * @param vertexBuffer Contains the position information as two vertexes. Start and end of the line to draw
     * @param colorBuffer  Contains the color of the line
     * @param unused
     */
    @Override
    public void render(FloatBuffer vertexBuffer, FloatBuffer colorBuffer, ByteBuffer unused) {
        setupShaderUsage();

        /**
         * We use the OpenGL methods to set the vertex information in the following order.
         * 1. The handle generated by the {@link MarkerDistanceShaderProgram}
         * 2. Size of the position information. As we operate in 3D space this is 3 (x,y,z) (but for OpenGL and matrix operations it could also be 4, as you need a 4 size vector for 4x4 matrix operations).
         * 3. Kind of the vector position data (Float, Double)
         * 4. Is the vector normalized?
         * 5. The distance in Bytes between each vertex information including the vertex itself. First
         *      thing to remember here is that we are very close to C programming. That is why everything
         *      is handled in bytes and why we try and optimize things. The other thing is that you might want
         *      to use your vertexBuffer as container for position and color information (eg: [pos(x,y,z),color(r,g,b),pos(x,y,z),...])
         *      That is why you need to specify the distance between each vertex. In this case the vertexBuffer only holds the position information
         *      So the distance in byte is position size (3 as described in point 2.) multiplied with bytes per float (4)
         * 6. The vertex information itself.
         */
        //camPosition.length * 4 bytes per float
        GLES20.glVertexAttribPointer(this.getPositionHandle(), positionDataSize, GLES20.GL_FLOAT, false,
                positionStrideBytes, vertexBuffer);
        GLES20.glEnableVertexAttribArray(this.getPositionHandle());


        /** Pass the color information to OpenGL
         * 1. The handle generated by the {@link MarkerDistanceShaderProgram}
         * 2. Pass in 1 as count of color vertexes (my line has only one color)
         * 3. The color information itself.
         */
        GLES20.glUniform4fv(this.getColorHandle(), 1, colorBuffer);
        GLES20.glLineWidth(this.lineWidth);

        //Finally draw the given vertex with the color as a line. The used information from the vertex
        // buffer starts at the beginning of the buffer (0) (Remember that the vertex could hold other information as well).
        // The position information contain (2) vertexes that need to be used. (Start and end of the line)
        GLES20.glDrawArrays(GLES20.GL_LINES, 0, 2);

        Log.e(TAG, "Shader Info: " + GLES20.glGetShaderInfoLog(getShaderProgramHandle()));
    }

}
